name: utkface_lab
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - scikit-learn
  - matplotlib
  - numpy
  - pandas
  - pillow
  - tensorboard
  - streamlit
  - pip:
    - opencv-python-headless
